In [1]:
using LinearAlgebra
methods(factorize)


# 11 methods for generic function "factorize":
[1] factorize(A::StridedArray{T, 2}) where T in LinearAlgebra at C:\Users\kacpe\AppData\Local\Programs\Julia 1.5.3\share\julia\stdlib\v1.5\LinearAlgebra\src\dense.jl:1207
[2] factorize(A::Adjoint) in LinearAlgebra at C:\Users\kacpe\AppData\Local\Programs\Julia 1.5.3\share\julia\stdlib\v1.5\LinearAlgebra\src\dense.jl:1283
[3] factorize(A::Transpose) in LinearAlgebra at C:\Users\kacpe\AppData\Local\Programs\Julia 1.5.3\share\julia\stdlib\v1.5\LinearAlgebra\src\dense.jl:1284
[4] factorize(A::LinearAlgebra.AbstractTriangular) in LinearAlgebra at C:\Users\kacpe\AppData\Local\Programs\Julia 1.5.3\share\julia\stdlib\v1.5\LinearAlgebra\src\triangular.jl:2676
[5] factorize(A::Union{Hermitian{Complex{Float64},var"#s828"}, Hermitian{Float64,var"#s828"}, Symmetric{Float64,var"#s828"}} where var"#s828"<:SparseArrays.AbstractSparseMatrixCSC) in SparseArrays at C:\Users\kacpe\AppData\Local\Programs\Julia 1.5.3\share\julia\stdlib\v1.5\SparseArrays\src\linalg.jl:1538
[6] factorize(A::Union{Hermitian{T,S}, Symmetric{T,S}} where S where T) in LinearAlgebra at C:\Users\kacpe\AppData\Local\Programs\Julia 1.5.3\share\julia\stdlib\v1.5\LinearAlgebra\src\symmetric.jl:634
[7] factorize(A::Tridiagonal) in LinearAlgebra at C:\Users\kacpe\AppData\Local\Programs\Julia 1.5.3\share\julia\stdlib\v1.5\LinearAlgebra\src\lu.jl:555
[8] factorize(D::Diagonal) in LinearAlgebra at C:\Users\kacpe\AppData\Local\Programs\Julia 1.5.3\share\julia\stdlib\v1.5\LinearAlgebra\src\diagonal.jl:121
[9] factorize(A::Bidiagonal) in LinearAlgebra at C:\Users\kacpe\AppData\Local\Programs\Julia 1.5.3\share\julia\stdlib\v1.5\LinearAlgebra\src\bidiag.jl:875
[10] factorize(S::SymTridiagonal) in LinearAlgebra at C:\Users\kacpe\AppData\Local\Programs\Julia 1.5.3\share\julia\stdlib\v1.5\LinearAlgebra\src\ldlt.jl:166
[11] factorize(A::SparseArrays.AbstractSparseMatrixCSC) in SparseArrays at C:\Users\kacpe\AppData\Local\Programs\Julia 1.5.3\share\julia\stdlib\v1.5\SparseArrays\src\linalg.jl:1508

In [8]:
x=[1; 2; 3; 4; 5; 6]
A = zeros(6,3)
A[:,3] = ones(6)
A
A[:,1] = x.^2


6-element Array{Int64,1}:
  1
  4
  9
 16
 25
 36

In [2]:
x = rand(1000)
A = rand(1000,1000)

1000×1000 Array{Float64,2}:
 0.517136   0.149953    0.508255   …  0.730812   0.742294  0.335116
 0.850711   0.407269    0.176958      0.548037   0.83208   0.307664
 0.15294    0.489132    0.790813      0.421145   0.702198  0.197562
 0.328974   0.953306    0.528284      0.114693   0.293622  0.88689
 0.341253   0.397289    0.0323014     0.199482   0.99335   0.653566
 0.0516092  0.497667    0.626383   …  0.0754926  0.682364  0.110418
 0.892419   0.282972    0.257752      0.399145   0.97552   0.485638
 0.404049   0.119319    0.110595      0.719971   0.921642  0.255809
 0.150156   0.129103    0.890861      0.847982   0.867755  0.731213
 0.497498   0.00932048  0.587959      0.251575   0.1141    0.0504509
 0.733272   0.0800332   0.71326    …  0.838878   0.545696  0.983639
 0.534782   0.930348    0.336254      0.178918   0.81758   0.818236
 0.604088   0.617067    0.751368      0.928072   0.342824  0.512634
 ⋮                                 ⋱                       
 0.720661   0.242977    0.23

In [5]:
b = A*x

1000-element Array{Float64,1}:
 237.37190940901115
 251.98189091055107
 245.23829015945813
 250.38191555580752
 229.98310395911207
 246.88551708603603
 247.55041451457544
 246.30366477893526
 248.48281306335753
 237.9818227403135
 259.9748475560494
 238.67978519367082
 243.62995673538336
   ⋮
 241.4684054529128
 242.9026097369165
 237.9054263661316
 237.26903727432028
 246.85671801834215
 244.98188896593365
 243.74626913754437
 248.87211855014172
 243.74822115617653
 248.21910994305503
 240.48887927438784
 240.81601817171335

In [7]:
@time inv(A) * b

  0.051854 seconds (6 allocations: 8.133 MiB)


1000-element Array{Float64,1}:
 0.5570129734684599
 0.5081087059138092
 0.7371168465772229
 0.8043165243953041
 0.5113562423962428
 0.8076910331000349
 0.5517998738686245
 0.3122400246555408
 0.43878252545975727
 0.02433162926550736
 0.7216691068072549
 0.9426575699060606
 0.2307987180613722
 ⋮
 0.34126725270224867
 0.5717379789849737
 0.647552360284088
 0.43030757573620804
 0.7471142552399925
 0.2677893104443356
 0.19685678663001482
 0.8037747243073241
 0.0948682213725931
 0.017092223862150924
 0.9060659502040931
 0.1407740015786807

In [9]:
@time A \ b

  0.026407 seconds (4 allocations: 7.645 MiB)


1000-element Array{Float64,1}:
 0.5570129734696937
 0.5081087059141275
 0.7371168465762291
 0.8043165243960549
 0.5113562423958545
 0.807691033098788
 0.5517998738690222
 0.3122400246554049
 0.43878252545951446
 0.024331629265417275
 0.7216691068078843
 0.9426575699048106
 0.23079871806047228
 ⋮
 0.34126725270182795
 0.5717379789849373
 0.647552360283806
 0.43030757573473954
 0.7471142552392176
 0.2677893104441701
 0.19685678663010608
 0.803774724307711
 0.09486822137225139
 0.01709222386282117
 0.9060659502040753
 0.14077400157842082

In [11]:
t0 = time()
Af = factorize(A)
Af \ b
print(time() - t0)

0.03299999237060547

In [57]:
f4(x) = ( x + 3 ) * ( x - 1 )^2
A = ones(10,3)
x = [i for i in 1:10]
y = [f4(i) for i in x]
A[:,1] = x.^2
A[:,2] = x

10-element Array{Int64,1}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

In [30]:
AF = factorize(A)


QRPivoted{Float64,Array{Float64,2}}
Q factor:
10×10 LinearAlgebra.QRPackedQ{Float64,Array{Float64,2}}:
 -0.00628285  -0.180555    0.765207   …  -0.0284868   -0.233895   -0.512314
 -0.0251314   -0.312143    0.425115       0.338725     0.449124    0.54828
 -0.0565456   -0.394764    0.155876      -0.335443    -0.16683     0.0721115
 -0.100526    -0.428418   -0.0425115     -0.00247151   0.0490448   0.109208
 -0.157071    -0.413105   -0.170046      -0.0807517   -0.0194093   0.0591343
 -0.226183    -0.348824   -0.226728   …  -0.139421    -0.0865541  -0.0143963
 -0.30786     -0.235576   -0.212558      -0.178479    -0.15239    -0.111384
 -0.402102    -0.0733617  -0.127535       0.802074    -0.216916   -0.231827
 -0.508911     0.13782     0.028341      -0.197761     0.719867   -0.375728
 -0.628285     0.397969    0.255069      -0.177986    -0.342041    0.456915
R factor:
3×3 Array{Float64,2}:
 -159.163  -19.0056   -2.4189
    0.0     -4.87713  -1.85096
    0.0      0.0       0.85023
permutation

In [33]:
AF.R\((Transpose(AF.Q)*y)[1:3])

3-element Array{Float64,1}:
  17.49999999999999
 -81.09999999999987
  88.79999999999959

In [34]:
A \ y

3-element Array{Float64,1}:
  17.499999999999996
 -81.09999999999998
  88.79999999999986

In [35]:
using Polynomials
fit(x,y, 2)

Polynomial(88.8000000000006 - 81.10000000000016*x + 17.50000000000001*x^2)

In [36]:
AF.R

3×3 Array{Float64,2}:
 -159.163  -19.0056   -2.4189
    0.0     -4.87713  -1.85096
    0.0      0.0       0.85023

In [127]:
function pseuinverse(A::Array{Float64,2})
    Q, R = qr(A)
    return (inv(R) * transpose(Q))
end

pseuinverse (generic function with 1 method)

In [136]:
A2 = rand(50,50)
C = pseuinverse(A2)
A2 * C


50×50 Array{Float64,2}:
  1.0           7.52268e-16   1.70131e-15  …   2.43394e-15  -2.47396e-15
 -1.32286e-16   1.0           7.74095e-16      1.83466e-15   1.0171e-16
 -4.57653e-16  -6.59652e-16   1.0              2.16153e-15   1.18386e-15
 -5.68672e-16   4.07225e-16   1.31124e-15      2.41992e-15   3.80131e-16
  1.98324e-15  -8.27331e-16  -3.48433e-15     -2.15614e-15   9.46342e-16
  4.86174e-16  -3.20842e-16  -4.35399e-16  …  -1.39886e-15  -1.32062e-15
  5.20261e-16  -1.10729e-15  -7.54509e-16     -2.05693e-15  -2.78777e-16
  2.3588e-16   -9.39819e-16  -1.44601e-15      1.05336e-15  -8.74268e-16
  2.47498e-17   7.42288e-16   5.97161e-16      1.76839e-16  -1.95685e-16
 -1.47948e-15  -8.8935e-16   -3.44623e-16      1.97123e-15  -4.93208e-16
 -1.02479e-17   4.07222e-16   1.57956e-15  …   7.35756e-17  -9.95222e-16
 -8.21438e-16  -1.03587e-15  -2.78353e-16      4.61747e-16  -1.98651e-15
  1.33341e-15   1.01986e-16  -3.13205e-15     -1.13931e-15   3.0583e-16
  ⋮                          

In [135]:
isapprox(A2, pseuinverse(pseuinverse(A2)))

true